# Generated by Django 4.2 on 2024-01-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_staff_page', 'Can view staff page')]},
        ),
    ]
