# Generated by Django 4.2 on 2024-01-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
        migrations.AlterModelOptions(
            name='warehousemanager',
            options={'verbose_name': 'WarehouseManager', 'verbose_name_plural': 'WarehouseManagers'},
        ),
    ]
