# Generated by Django 4.2 on 2024-01-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staff_options_alter_warehousemanager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_staff_page', 'Can view staff page'), ('view_admin_page', 'Can view admin pages')]},
        ),
    ]
