# Generated by Django 5.0.1 on 2024-01-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('receip_date', models.DateTimeField(blank=True, null=True)),
                ('device_code', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('نصب', 'نصب'), ('انصراف', 'انصراف'), ('معیوب', 'معیوب')], max_length=10)),
                ('recepted', models.BooleanField(null=True)),
                ('installed', models.BooleanField(null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.staff')),
            ],
        ),
    ]
