# Generated by Django 4.2 on 2024-01-04 07:18

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='receip_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
