# Generated by Django 4.2 on 2024-01-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_device_created_date_alter_device_receip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('I', 'Installation'), ('O', 'Opt Out'), ('D', 'Defective')], max_length=1),
        ),
    ]
