# Generated by Django 4.2 on 2024-01-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
